import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const title = "Olympiad Tracker — Competition calendar & parser";
const description = "Parse academic competition pages, extract dates & details, and add events to your calendar.";

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <title>{title}</title>
          <meta name="description" content={description} />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />

          {/* Open Graph */}
          <meta property="og:type" content="website" />
          <meta property="og:title" content={title} />
          <meta property="og:description" content={description} />
          <meta property="og:image" content={`https://trackolymp.tech/og-image.png`} />
          <meta property="og:url" content="https://trackolymp.tech" />
          <meta property="og:site_name" content="Olympiad Tracker"/>

          {/* Twitter */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content={title} />
          <meta name="twitter:description" content={description} />

          {/*<meta name="robots" content="index, follow" />
          <link rel="manifest" href="/site.webmanifest" />*/}
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SpeedInsights/>
          <header className="p-4 relative">
            <h1 className="text-2xl font-bold rounded text-center w-full">
              Trackolymp.tech
            </h1>
            <div className="absolute top-0.5 bottom-2 right-4 flex items-center gap-4 mr-4 h-full">
              <SignedOut>
                <SignInButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <Link href="/dashboard" className="rounded-full border border-[#6c47ff] px-4 py-2 text-sm font-medium text-[#6c47ff] transition hover:bg-[#f2edff]">
                  Dashboard
                </Link>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
